# tinyim
python main_sacl.py --dataset tinyimagenet --freeze_backbone --backbone_checkpoint_path /checkpoint_last.pth --num_layers 4 --rho_const 1e3 --s_init_t 3.5 --first_conv --no-drop_maxpool --base_lr 0.25 --weight_decay 0  --num_workers 20 --hidden_dim 1024 --out_features 2 --criterion sacl_batchmix --batch_size 128 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear 
python main_sacl.py --dataset tinyimagenet --freeze_backbone --backbone_checkpoint_path /checkpoint_last.pth --num_layers 4 --rho_const 1e3 --s_init_t 2.25 --first_conv --no-drop_maxpool --base_lr 0.25 --weight_decay 0  --num_workers 20 --hidden_dim 1024 --out_features 2 --criterion sacl --batch_size 128 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear 
python main_sacl.py --dataset tinyimagenet --freeze_backbone --backbone_checkpoint_path /checkpoint_last.pth --num_layers 4 --rho_const 1e5 --s_init_t 2.25 --first_conv --no-drop_maxpool --base_lr 0.05 --weight_decay 0  --num_workers 20 --hidden_dim 1024 --out_features 2 --criterion scl --batch_size 128 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear
python main_sacl.py --dataset tinyimagenet --freeze_backbone --backbone_checkpoint_path /checkpoint_last.pth --num_layers 4 --first_conv --no-drop_maxpool --base_lr 0.25 --weight_decay 0 --num_workers 20 --hidden_dim 1024 --out_features 2 --criterion simclr --batch_size 128 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear

# stl10
python main_sacl.py --dataset stl10 --freeze_backbone --backbone_checkpoint_path /checkpoint_last.pth --num_layers 4 --rho_const 1e3 --s_init_t 3.5 --first_conv --no-drop_maxpool --base_lr 0.25 --weight_decay 0  --num_workers 20 --hidden_dim 1024 --out_features 2 --criterion sacl_batchmix --batch_size 128 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear 
python main_sacl.py --dataset stl10 --freeze_backbone --backbone_checkpoint_path /checkpoint_last.pth --num_layers 4 --rho_const 1e4 --s_init_t 2.0 --first_conv --no-drop_maxpool --base_lr 0.25 --weight_decay 0  --num_workers 20 --hidden_dim 1024 --out_features 2 --criterion sacl --batch_size 128 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear 
python main_sacl.py --dataset stl10 --freeze_backbone --backbone_checkpoint_path /checkpoint_last.pth --num_layers 4 --rho_const 1e4 --s_init_t 2 --first_conv --no-drop_maxpool --base_lr 0.05 --weight_decay 0  --num_workers 20 --hidden_dim 1024 --out_features 2 --criterion scl --batch_size 128 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear
python main_sacl.py --dataset stl10 --freeze_backbone --backbone_checkpoint_path /checkpoint_last.pth --num_layers 4 --first_conv --no-drop_maxpool --base_lr 0.25 --weight_decay 0  --num_workers 20 --hidden_dim 1024 --out_features 2 --criterion simclr --batch_size 128 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear 


python main_sacl.py --dataset tinyimagenet --freeze_backbone --backbone_checkpoint_path logs/pretrain/2024_06_16_21_43_55_scl_single_sFalse_cauchy_tinyimagenet_128_epochs_1000_resnet18_lr0.025_temp0.5_alpha0.125_rho0.9987216363055289_sinit1e-08_outfeatures128/checkpoint_last.pth --num_layers 4 --rho_const 1e5 --s_init_t 2.25 --first_conv --no-drop_maxpool --base_lr 0.05 --weight_decay 0  --num_workers 20 --hidden_dim 1024 --out_features 2 --criterion scl --batch_size 128 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear
python main_sacl.py --dataset stl10 --freeze_backbone --backbone_checkpoint_path logs/pretrain/2024_06_15_23_12_37_scl_single_sFalse_cauchy_stl10_128_epochs_1000_resnet18_lr0.025_temp0.5_alpha0.125_rho0.9988403486201961_sinit9.070294784580499e-09_outfeatures128/checkpoint_last.pth --num_layers 4 --rho_const 1e4 --s_init_t 2 --first_conv --no-drop_maxpool --base_lr 0.05 --weight_decay 0  --num_workers 20 --hidden_dim 1024 --out_features 2 --criterion scl --batch_size 128 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear
