# tinyim
python main_sacl.py --dataset tinyimagenet --knn_feature_type output_features --freeze_backbone --backbone_checkpoint_path /checkpoint_last.pth --num_layers 4 --rho_const 1e3 --s_init_t 3.5 --first_conv --no-drop_maxpool --base_lr 0.25 --weight_decay 0 --no-use_fp32 --val_split 0.0 --num_workers 20 --knn_k 15 --knn_fx_distance euclidean --hidden_dim 1024 --knn_weights uniform --temp 0.5 --out_features 2 --criterion sacl_batchmix --batch_size 128 --validate_interval 10 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear --no-wandb_logging
python main_sacl.py --dataset tinyimagenet --knn_feature_type output_features --freeze_backbone --backbone_checkpoint_path /checkpoint_last.pth --num_layers 4 --rho_const 1e3 --s_init_t 2.25 --first_conv --no-drop_maxpool --base_lr 0.25 --weight_decay 0 --no-use_fp32 --val_split 0.0 --num_workers 20 --knn_k 15 --knn_fx_distance euclidean --hidden_dim 1024 --knn_weights uniform --temp 0.5 --out_features 2 --criterion sacl --batch_size 128 --validate_interval 10 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear --no-wandb_logging
python main_sacl.py --dataset tinyimagenet --knn_feature_type output_features --freeze_backbone --backbone_checkpoint_path /checkpoint_last.pth --num_layers 4 --rho_const 1e5 --s_init_t 2.25 --no-single_s --first_conv --no-drop_maxpool --base_lr 0.25 --weight_decay 0 --no-use_fp32 --val_split 0.0 --num_workers 20 --knn_k 15 --knn_fx_distance euclidean --hidden_dim 1024 --knn_weights uniform --temp 0.5 --out_features 2 --criterion scl --batch_size 128 --validate_interval 10 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear --no-wandb_logging
python main_sacl.py --dataset tinyimagenet --knn_feature_type output_features --freeze_backbone --backbone_checkpoint_path /checkpoint_last.pth --num_layers 4 --first_conv --no-drop_maxpool --base_lr 0.25 --weight_decay 0 --no-use_fp32 --val_split 0.0 --num_workers 20 --knn_k 15 --knn_fx_distance euclidean --hidden_dim 1024 --knn_weights uniform --temp 0.5 --out_features 2 --criterion simclr --batch_size 128 --validate_interval 10 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear --no-wandb_logging

# stl10
python main_sacl.py --dataset stl10 --knn_feature_type output_features --freeze_backbone --backbone_checkpoint_path /checkpoint_last.pth --num_layers 4 --rho_const 1e3 --s_init_t 3.5 --first_conv --no-drop_maxpool --base_lr 0.25 --weight_decay 0 --no-use_fp32 --val_split 0.0 --num_workers 20 --knn_k 15 --knn_fx_distance euclidean --hidden_dim 1024 --knn_weights uniform --temp 0.5 --out_features 2 --criterion sacl_batchmix --batch_size 128 --validate_interval 10 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear --no-wandb_logging
python main_sacl.py --dataset stl10 --knn_feature_type output_features --freeze_backbone --backbone_checkpoint_path /checkpoint_last.pth --num_layers 4 --rho_const 1e4 --s_init_t 2.0 --first_conv --no-drop_maxpool --base_lr 0.25 --weight_decay 0 --no-use_fp32 --val_split 0.0 --num_workers 20 --knn_k 15 --knn_fx_distance euclidean --hidden_dim 1024 --knn_weights uniform --temp 0.5 --out_features 2 --criterion sacl --batch_size 128 --validate_interval 10 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear --no-wandb_logging
python main_sacl.py --dataset stl10 --knn_feature_type output_features --freeze_backbone --backbone_checkpoint_path /checkpoint_last.pth --num_layers 4 --rho_const 1e4 --s_init_t 2 --no-single_s --first_conv --no-drop_maxpool --base_lr 0.25 --weight_decay 0 --no-use_fp32 --val_split 0.0 --num_workers 20 --knn_k 15 --knn_fx_distance euclidean --hidden_dim 1024 --knn_weights uniform --temp 0.5 --out_features 2 --criterion scl --batch_size 128 --validate_interval 10 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear --no-wandb_logging
python main_sacl.py --dataset stl10 --knn_feature_type output_features --freeze_backbone --backbone_checkpoint_path /checkpoint_last.pth --num_layers 4 --first_conv --no-drop_maxpool --base_lr 0.25 --weight_decay 0 --no-use_fp32 --val_split 0.0 --num_workers 20 --knn_k 15 --knn_fx_distance euclidean --hidden_dim 1024 --knn_weights uniform --temp 0.5 --out_features 2 --criterion simclr --batch_size 128 --validate_interval 10 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear --no-wandb_logging



python main_sacl.py --dataset tinyimagenet --knn_feature_type output_features --freeze_backbone --backbone_checkpoint_path logs/pretrain/2024_06_08_10_46_36_scl_single_sFalse_cauchy_tinyimagenet_128_epochs_1000_resnet18_lr0.125_temp0.5_alpha0.25_rho0.9873617693522907_sinit1e-08_outfeatures128/checkpoint_last.pth --num_layers 4 --rho_const 1e5 --s_init_t 2.25 --no-single_s --first_conv --no-drop_maxpool --base_lr 0.25 --weight_decay 0 --no-use_fp32 --val_split 0.0 --num_workers 20 --knn_k 15 --knn_fx_distance euclidean --hidden_dim 1024 --knn_weights uniform --temp 0.5 --out_features 2 --criterion scl --batch_size 128 --validate_interval 10 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear --no-wandb_logging
python main_sacl.py --dataset stl10 --knn_feature_type output_features --freeze_backbone --backbone_checkpoint_path logs/pretrain/2024_06_07_23_47_44_scl_single_sFalse_cauchy_stl10_128_epochs_1000_resnet18_lr0.125_temp0.5_alpha0.25_rho0.9885232672823455_sinit9.070294784580499e-09_outfeatures128/checkpoint_last.pth --num_layers 4 --rho_const 1e4 --s_init_t 2 --no-single_s --first_conv --no-drop_maxpool --base_lr 0.25 --weight_decay 0 --no-use_fp32 --val_split 0.0 --num_workers 20 --knn_k 15 --knn_fx_distance euclidean --hidden_dim 1024 --knn_weights uniform --temp 0.5 --out_features 2 --criterion scl --batch_size 128 --validate_interval 10 --metric cauchy --epochs 250 --momentum 0.9 --lr_anneal cosine --warmup_epochs 10 --lr_scale linear --no-wandb_logging
